// Package mimetype provides MIME type lookup for file extensions.
//
// Source: http://svn.apache.org/viewvc/httpd/httpd/trunk/docs/conf/mime.types
// Licensed under the Unlicense: https://unlicense.org/UNLICENSE
package mimetype

// extToMIME maps file extensions (lowercase, with leading dot) to MIME types.
var extToMIME = map[string]string{
	// application
	".gz":       "application/gzip",
	".js":       "application/javascript",
	".cjs":      "application/javascript",
	".mjs":      "application/javascript",
	".json":     "application/json",
	".ogx":      "application/ogg",
	".pdf":      "application/pdf",
	".ai":       "application/postscript",
	".eps":      "application/postscript",
	".eps2":     "application/postscript",
	".eps3":     "application/postscript",
	".epsf":     "application/postscript",
	".epsi":     "application/postscript",
	".ps":       "application/postscript",
	".wasm":     "application/wasm",
	".torrent":  "application/x-bittorrent",
	".deb":      "application/x-debian-package",
	".udeb":     "application/x-debian-package",
	".gsf":      "application/x-font",
	".pfa":      "application/x-font",
	".pfb":      "application/x-font",
	".gtar":     "application/x-gtar",
	".taz":      "application/x-gtar-compressed",
	".tgz":      "application/x-gtar-compressed",
	".iso":      "application/x-iso9660-image",
	".rpm":      "application/x-redhat-package-manager",
	".rss":      "application/x-rss+xml",
	".tar":      "application/x-tar",
	".xz":       "application/x-xz",
	".xht":      "application/xhtml+xml",
	".xhtml":    "application/xhtml+xml",
	".xml":      "application/xml",
	".xsd":      "application/xml",
	".zip":      "application/zip",
	// audio
	".adp":  "audio/adpcm",
	".amr":  "audio/amr",
	".awb":  "audio/amr-wb",
	".axa":  "audio/annodex",
	".au":   "audio/basic",
	".snd":  "audio/basic",
	".kar":  "audio/midi",
	".mid":  "audio/midi",
	".midi": "audio/midi",
	".rmi":  "audio/midi",
	".m4a":  "audio/mp4",
	".mp4a": "audio/mp4",
	".m2a":  "audio/mpeg",
	".m3a":  "audio/mpeg",
	".mp2":  "audio/mpeg",
	".mp2a": "audio/mpeg",
	".mp3":  "audio/mpeg",
	".mpega": "audio/mpeg",
	".mpga": "audio/mpeg",
	".oga":  "audio/ogg",
	".ogg":  "audio/ogg",
	".opus": "audio/ogg",
	".spx":  "audio/ogg",
	".sid":  "audio/prs.sid",
	".s3m":  "audio/s3m",
	".sil":  "audio/silk",
	".weba": "audio/webm",
	".aac":  "audio/x-aac",
	".aif":  "audio/x-aiff",
	".aifc": "audio/x-aiff",
	".aiff": "audio/x-aiff",
	".caf":  "audio/x-caf",
	".csd":  "audio/x-csound",
	".orc":  "audio/x-csound",
	".sco":  "audio/x-csound",
	".flac": "audio/x-flac",
	".gsm":  "audio/x-gsm",
	".mka":  "audio/x-matroska",
	".m3u":  "audio/x-mpegurl",
	".wax":  "audio/x-ms-wax",
	".wma":  "audio/x-ms-wma",
	".ra":   "audio/x-pn-realaudio",
	".ram":  "audio/x-pn-realaudio",
	".rm":   "audio/x-pn-realaudio",
	".pls":  "audio/x-scpls",
	".sd2":  "audio/x-sd2",
	".wav":  "audio/x-wav",
	".xm":   "audio/xm",
	// font
	".ttc":   "font/collection",
	".otf":   "font/otf",
	".ttf":   "font/ttf",
	".woff":  "font/woff",
	".woff2": "font/woff2",
	// image
	".gif":  "image/gif",
	".jp2":  "image/jp2",
	".jpg2": "image/jp2",
	".jpe":  "image/jpeg",
	".jpeg": "image/jpeg",
	".jpg":  "image/jpeg",
	".jpf":  "image/jpx",
	".jpx":  "image/jpx",
	".png":  "image/png",
	".svg":  "image/svg+xml",
	".svgz": "image/svg+xml",
	".tif":  "image/tiff",
	".tiff": "image/tiff",
	".webp": "image/webp",
	".ico":  "image/x-icon",
	// message
	".eml":  "message/rfc822",
	".mime": "message/rfc822",
	// text
	".adoc":    "text/asciidoc",
	".css":     "text/css",
	".csv":     "text/csv",
	".htm":     "text/html",
	".html":    "text/html",
	".shtml":   "text/html",
	".markdown": "text/markdown",
	".md":      "text/markdown",
	".mml":  "text/mathml",
	".asc":  "text/plain",
	".log":  "text/plain",
	".pot":  "text/plain",
	".text": "text/plain",
	".txt":  "text/plain",
	".rtx":  "text/richtext",
	".tsv":  "text/tab-separated-values",
	".man":  "text/troff",
	".me":   "text/troff",
	".ms":   "text/troff",
	".roff": "text/troff",
	".t":    "text/troff",
	".tr":   "text/troff",
	".c":    "text/x-c",
	".c++":  "text/x-c",
	".cc":   "text/x-c",
	".cpp":  "text/x-c",
	".cxx":  "text/x-c",
	".h":    "text/x-c",
	".h++":  "text/x-c",
	".hh":   "text/x-c",
	".hpp":  "text/x-c",
	".hxx":  "text/x-c",
	".diff":  "text/x-diff",
	".patch": "text/x-diff",
	".sass":  "text/x-sass",
	".scss":  "text/x-scss",
	// video
	".mp4":  "video/mp4",
	".ogv":  "video/ogg",
	".webm": "video/webm",
	".mkv":  "video/x-matroska",
}

// Lookup returns the MIME type for the given file extension.
// The extension should include the leading dot (e.g. ".pdf").
// Returns "" if no mapping is found.
func Lookup(ext string) string {
	return extToMIME[ext]
}

// IsPassthrough reports whether the given file extension is known
// in the MIME type table, meaning it should be served as-is.
func IsPassthrough(ext string) bool {
	_, ok := extToMIME[ext]
	return ok
}
