# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: make build
      - name: Test
        run: make bench # test
      - name: Vet
        run: make vet

  Ping-IRC:
    # Always run, announce trunk and tag pushes
    if: ${{ always() && github.event_name == 'push' && (github.ref == 'refs/heads/trunk' || github.ref_type == 'tag') }}
    runs-on: ubuntu-latest
    needs: [ build-and-test ]
    steps:
    - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
    - run: git fetch -f --tags  # Fix actions/checkout#290
    - name: Ping-IRC
      if: ${{ always() && !env.ACT }}  # IRCBOT_JOBS indicates 'success'
      env: { IRCBOT_JOBS: "${{ join(needs.*.result, ' ') }}" }
      run: .github/workflows/ircbot.py -q -j "#Anklang" -G
