# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - name: Build
        run: make build
      - name: Test
        run: make bench # test
      - name: Vet
        run: make vet
